IRMAS_N_CLASSES = 11
TRAIN_SPLIT = 0.85
VALIDATION_SPLIT = 0.15
N_TRAINING_SET = 6705
MAX_EPOCH_NUM = 400
EARLY_STOPPING_EPOCH = 20
BATCH_SIZE = 16


N_SEGMENTS_PER_TRAINING_FILE = 1
SAMPLES_PER_EPOCH = N_TRAINING_SET * N_SEGMENTS_PER_TRAINING_FILE * TRAIN_SPLIT
SAMPLES_PER_VALIDATION = N_TRAINING_SET * N_SEGMENTS_PER_TRAINING_FILE * VALIDATION_SPLIT
N_MEL_BANDS = 96
SEGMENT_DUR = 128


IRMAS_TRAIN_FEATURE_BASEPATH = '/home/olga/IRMAS/IRMAS-TrainingData-Features/singlelayer'
IRMAS_TEST_FEATURE_BASEPATH = '/home/olga/IRMAS/IRMAS-TestingData-Features/singlelayer'
IRMAS_TRAINING_META_PATH = './IRMAS-Sample/irmas_train_meta.csv'
IRMAS_TESTING_META_PATH = './IRMAS-Sample/irmas_test_meta.csv'
MODEL_WEIGHT_BASEPATH = './weights/'
